apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-rapids-yunikorn
  namespace: default
spec:
  batchScheduler: yunikorn
  batchSchedulerOptions:
    queue: root.default
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: kubedai/spark-rapids-k8s-cuda:spark-3.5.1_rapids-24.08.1_cuda-11.8_java-8  # Replace with your image URI
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/sparkRapidsPlugin/gpu_rapids_performance_test.py" # Change this to S3 path
  mainClass: org.apache.spark.deploy.PythonRunner
  sparkVersion: "3.5.1"
  restartPolicy:
    type: Never
  sparkConf:
    "spark.ui.port": "4045"
    "spark.rapids.sql.concurrentGpuTasks": "2" # Tweak this to 2
    "spark.executor.resource.gpu.amount": "1"
    "spark.task.resource.gpu.amount": "1"
    "spark.executor.memory": "10g"
    "spark.rapids.memory.pinnedPool.size": "2g"
    "spark.executor.memoryOverhead": "3g"
    "spark.sql.files.maxPartitionBytes": "512m"
    "spark.sql.shuffle.partitions": "10"
    "spark.plugins": "com.nvidia.spark.SQLPlugin"
    "spark.shuffle.manager": "com.nvidia.spark.rapids.spark351.RapidsShuffleManager"
    "spark.executor.resource.gpu.discoveryScript": "/opt/sparkRapidsPlugin/getGpusResources.sh"
    "spark.executor.resource.gpu.vendor": "nvidia.com"
    "spark.executor.extraLibraryPath": "/usr/local/cuda/lib:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/targets/x86_64-linux/lib:/usr/lib/hadoop/lib/native:/usr/lib/hadooplzo/lib/native:/docker/usr/lib/hadoop/lib/native:/docker/usr/lib/hadoop-lzo/lib/native"
    "spark.task.cpus": "1"
    "spark.dynamicAllocation.enabled": "false"
    # "spark.rapids.cloudSchemes": "s3,s3a,gs"  # Optional for cloud file systems
    # "spark.rapids.memory.gpu.maxAllocFraction": "0.9"  # Optional memory tuning
    # "spark.rapids.sql.batchSizeBytes": "512m"  # Optional batch size tuning
    # "spark.rapids.sql.multiThreadedRead.numThreads": "20"  # Tuning thread count for parallel reads
    # "spark.rapids.sql.shuffle.spillThreads": "8"  # Optional tuning for shuffle spill threads
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "2g"
    labels:
      version: "3.5.1"
    serviceAccount: spark-operator-spark # default one
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "10g"
    gpu:
      name: "nvidia.com/gpu"
      quantity: 1
    labels:
      version: "3.5.1"
    volumeMounts:
      - name: spark-local-dir-1
        mountPath: /data1
    initContainers:
      - name: volume-permission
        image: public.ecr.aws/docker/library/busybox
        command: ['sh', '-c', 'mkdir -p /data1; chown -R 185:185 /data1']
        volumeMounts:
          - name: spark-local-dir-1
            mountPath: /data1
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  volumes:
    - name: spark-local-dir-1
      hostPath:
        path: "/mnt/k8s-disks/0"
        type: DirectoryOrCreate
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
